---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Prepare | TESTING NOT ENABLED ⚠'
      when: not secure_boot_manual_testing_enable
      ansible.builtin.debug:
        msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │      TEST WILL NOT EXECUTE UNLESS IT IS EXPLICITLY ENABLED.       │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ Enable live API commands:
          │
          │   secure_boot_manual_testing_enable=true
          │
          │ Example:
          │
          │   molecule converge -s manual_vm_firmware_validation -- -v -e \
          │       'secure_boot_manual_testing_enable=true'
          │

    - name: 'Converge | apply r_pufky.deb.secure_boot'
      when: secure_boot_manual_testing_enable
      ansible.builtin.include_role:
        name: 'r_pufky.deb.secure_boot'
