---
# yamllint disable rule:line-length
- name: 'Manual VM firmware validation | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Manual VM firmware validation | prepare | TESTING NOT ENABLED'
      when: not secure_boot_manual_testing_enable
      ansible.builtin.debug:
        msg: |
          TEST WILL NOT EXECUTE UNLESS IT IS EXPLICITLY ENABLED.

          Set secure_boot_manual_testing_enable: true to test live API commands.

            molecule converge -s manual_vm_firmware_validation -- -v -e 'secure_boot_manual_testing_enable=true'
