---
###############################################################################
# Prepare
###############################################################################
# Testing requires ansible public keys. Generate keys for testing.

- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | cache'

    - name: 'Prepare | generate test ssh keys'
      ansible.builtin.command:
        argv:
          - 'ssh-keygen'
          - '-t'
          - 'ed25519'
          - '-C'
          - 'ansible@example.com'
          - '-f'
          - '{{ _test_cache }}/id'
          - '-q'
          - '-N'
          - '""'
        creates: '{{ _test_cache }}/id'
