---
# yamllint disable rule:line-length
###############################################################################
# MOK Key Management (Machine Owners Key)
###############################################################################
# Write custom key if it is defined, generate a new key if it doesn't exist.
#
# Key generation uses defaults from Debian DKMS auto generation.
#
# Args:
#   _secure_boot_public: str - Location for selected public key.
#   _secure_boot_private: str - Location for selected private key.
#
# Reference:
# * https://wiki.debian.org/SecureBoot#DKMS_and_secure_boot
# * https://github.com/jiazhang0/meta-efi-secure-boot/blob/master/README.md#mokutil-and-mok-manager
# * https://media.defense.gov/2023/Mar/20/2003182401/-1/-1/0/CTR-UEFI-SECURE-BOOT-CUSTOMIZATION-20230317.PDF
# yamllint enable rule:line-length

- name: 'MOK | write custom key'
  when: secure_boot_public | length > 0
  block:
    - name: 'MOK | write custom key | generate directories'
      ansible.builtin.file:
        path: '{{ secure_boot_key_location }}'
        owner: 'root'
        group: 'root'
        mode: '0755'
        recurse: true
        state: 'directory'
      become: true

    - name: 'MOK | write custom key | {{ _secure_boot_private }}'
      ansible.builtin.file:
        path: '{{ _secure_boot_private }}'
        owner: 'root'
        group: 'root'
        mode: '0600'
      become: true

    - name: 'MOK | write custom key | {{ _secure_boot_public }}'
      ansible.builtin.file:
        path: '{{ _secure_boot_public }}'
        owner: 'root'
        group: 'root'
        mode: '0644'
      become: true

# Create MOK key (DER signing)
- name: 'MOK | generate new {{ _secure_boot_private }}'
  ansible.builtin.command:
    argv:
      - 'openssl'
      - 'req'
      - '-nodes'
      - '-new'
      - '-x509'
      - '-newkey'
      - '{{ secure_boot_role_mok_algorithm }}'
      - '-outform'
      - '{{ secure_boot_role_mok_format }}'
      - '-days'
      - '{{ secure_boot_role_mok_expiration }}'
      - '-subj'
      - '/CN={{ secure_boot_role_mok_common_name }}/'
      - '-keyout'
      - '{{ _secure_boot_private }}'
      - '-out'
      - '{{ _secure_boot_public }}'
    creates: '{{ _secure_boot_private }}'
  changed_when: true
