---
# yamllint disable rule:line-length
###############################################################################
# Reset Secure Boot State
###############################################################################
# Clears user certificates from secure boot. Requires reboot.
#
# Generates:
#   _secure_boot_state: bool - validation enabled
#   _secure_boot_public: str - location for selected public key
#   _secure_boot_private: str - location for selected private key
#   _secure_boot_hash: str - hashed secure boot password
#   _secure_boot_key_exists: stat - specified MOK key file exists
#   _secure_boot_enrolled: bool - if key is enrolled (loaded) this boot cycle
#   _secure_boot_validation: bool - if signature validation has been changed

- name: 'Reset secure boot | clear secure boot keys'
  block:
    - name: 'Reset secure boot | touch hash file'
      ansible.builtin.copy:
        dest: '{{ secure_boot_role_tmp_hash }}'
        content: '{{ _secure_boot_hash }}'
        owner: 'root'
        group: 'root'
        mode: '0600'

    - name: 'Reset secure boot | clear existing keys'
      ansible.builtin.command: '{{ secure_boot_role_mokutil }} --reset --hash-file {{ secure_boot_role_tmp_hash }}'
      changed_when: true

    - name: 'Reset secure boot | ACTION REQUIRED'
      ansible.builtin.debug:
        msg: |
          Secure boot user keys have been cleared.

          MokManager will appear on boot; use secure_boot_password.

          ACTION REQUIRED:
            Reset MOK > Erase all stored keys in MokList? > Yes

    - name: 'Reset secure boot | REBOOT'
      when: >
        not secure_boot_halt_enable and
        not secure_boot_testing_enable
      ansible.builtin.reboot:
        reboot_timeout: '{{ secure_boot_reboot_timeout }}'

    - name: 'Reset secure boot | HALT'
      when: secure_boot_halt_enable
      ansible.builtin.fail:
        msg: |
          ROLE HALTED for manual interaction.

          Set secure_boot_halt_enable=false to disable this.
  always:
    - name: 'Reset| remove hash file'
      ansible.builtin.file:
        path: '{{ secure_boot_role_tmp_hash }}'
        state: 'absent'
