---
# Forcing reset will force a reboot before configuring settings. This should
# appear as a 'default' run with a --reset command before operations.
#
# State: (no_pre_keys_no_pre_secure_boot)
# * pre-enabled secure boot? false
# * pre-enrolled keys? false
dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        secure_boot_testing_enable: true
        secure_boot_password: 'ValidPassword'
        secure_boot_reset: true
platforms:
  - name: 'secure_boot-debian-12-reset'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    # - 'idempotence'  # hashed password file always regenerated if needed
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
