---
# yamllint disable rule:line-length
- name: 'No actions | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'No actions | verify | query mokutil log'
      ansible.builtin.slurp:
        path: '/tmp/mokutil.log'
      register: _test_secure_boot_mokutil_log

    - name: 'No actions | verify | parse mokutil log'
      ansible.builtin.set_fact:
        _test_secure_boot_log: '{{ _test_secure_boot_mokutil_log.content | b64decode }}'

    - name: 'No actions | verify | assert secure boot options toggled'
      ansible.builtin.assert:
        that:
          - '"--generate-hash" in _test_secure_boot_log'
          - '"--test-key" in _test_secure_boot_log'
          - '"--reset" in _test_secure_boot_log'
          - '"--import" in _test_secure_boot_log'
          - '"--enable-validation" in _test_secure_boot_log'
        fail_msg: >
          mokutil should have the following call log:
            --generate-hash=ValidPassword
            --reset --hash-file /tmp/.mokhash
            --sb-state
            --test-key /var/lib/dkms/mok.pub
            --timeout -1
            --import /var/lib/dkms/mok.pub --hash-file /tmp/.mokhash
            --timeout -1
            --enable-validation --hash-file /tmp/.mokhash
