---
# yamllint disable rule:line-length
- name: 'No actions | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'No actions | converge | inject mock mokutil'
      ansible.builtin.template:
        src: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/templates/mokutil.j2'
        dest: '/usr/bin/mokutil'
        owner: 'root'
        group: 'root'
        mode: '0755'
      vars:
        test_secure_boot: true
        test_test_key: true

    - name: 'No action | converge | inject /var/lib/dkms'
      ansible.builtin.file:
        dest: '/var/lib/dkms'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'
        recurse: true

    - name: 'No actions | converge | inject mock mok.key'
      ansible.builtin.copy:
        src: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/files/mok.key'
        dest: '/var/lib/dkms/mok.key'
        owner: 'root'
        group: 'root'
        mode: '0400'

    - name: 'No actions | converge | inject mock mok.key'
      ansible.builtin.copy:
        src: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/files/mok.pub'
        dest: '/var/lib/dkms/mok.pub'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'No actions | converge | apply r_pufky.srv.secure_boot'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.secure_boot'
      vars:
        # remove mokutil package from install
        secure_boot_role_packages:
          - 'openssl'
          - 'dkms'
