---
# yamllint disable rule:line-length
###############################################################################
# Prepare
###############################################################################
# Testing requires a valid certificate. Generate a test certificate.
#
# Reference:
# * https://wiki.debian.org/SecureBoot#MOK_-_Machine_Owner_Key
# * https://gist.github.com/rquackenbush/53ff432567699b21c86f3360fb4ec7f0
# * https://superuser.com/questions/226192/avoid-password-prompt-for-keys-and-prompts-for-dn-information
# yamllint enable rule:line-length

- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | cache'

    - name: 'Prepare | generate test certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'req'
          - '-new'
          - '-x509'
          - '-newkey'
          - 'rsa:4096'
          - '-nodes'
          - '-days'
          - '36500'
          - '-subj'
          - '/C=US/ST=NY/L=NY/O=test/CN=test.example.com'
          - '-keyout'
          - '{{ _test_cache }}/mok.key'
          - '-outform'
          - 'DER'
          - '-out'
          - '{{ _test_cache }}/mok.der'
        creates: '{{ _test_cache }}/mok.key'

    - name: 'Prepare | sign test certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'x509'
          - '-inform'
          - 'der'
          - '-in'
          - '{{ _test_cache }}/mok.der'
          - '-out'
          - '{{ _test_cache }}/mok.pub'
        creates: '{{ _test_cache }}/mok.pub'
